### ISSUE TITLE
AttributeError: module 'numpy.typing' has no attribute 'NDArray'

### ISSUE THREAD

**Issue by lmr07** [LeCAR-Lab/ABS#4]
While doing this line "python scripts/train.py --task=go1_pos_rough --max_iterations=4000 "(I strictly executed the codelines before this one and there is no mistake), this error jumps out.
I found that when I change the numpy version to 1.21(1.20 is not OK) the ploblem is fixed.

**Comment by TairanHe** [comment]
Updated the numpy version in the README to 1.21
